/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SistemPakar;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author admin01
 */
public class dashboard_admin extends javax.swing.JFrame {
private void load_table(){
        // membuat tampilan model tabel
        tabelPenyakit model = new tabelPenyakit();
        model.addColumn("No");
        model.addColumn("Nama");
        model.addColumn("NIM");
        model.addColumn("Jurusan");
        model.addColumn("Alamat");
        model.addColumn("Phone");
        
        //menampilkan data database kedalam tabel
        try {
            int no=1;
            String sql = "select * from penyakit";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5)});
            }
            tabelPenyakit.setModel(model);
        } catch (Exception e) {
        }
    /**
     * Creates new form dashboard_admin
     */
    public dashboard_admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgWhite = new javax.swing.JPanel();
        navbar = new javax.swing.JPanel();
        sistemPakar = new javax.swing.JLabel();
        btnKeluar = new javax.swing.JButton();
        dataPenyakit = new javax.swing.JLabel();
        btnTambahPenyakit = new javax.swing.JButton();
        dataGejala = new javax.swing.JLabel();
        btnTambahGejala = new javax.swing.JButton();
        dataAturan = new javax.swing.JLabel();
        btnTambahAturan = new javax.swing.JButton();
        scrollAturan = new javax.swing.JScrollPane();
        tabelAturan = new javax.swing.JTable();
        dataUser = new javax.swing.JLabel();
        btnTambahUser = new javax.swing.JButton();
        scrollUser = new javax.swing.JScrollPane();
        tabelUser = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bgWhite.setBackground(new java.awt.Color(254, 254, 254));

        navbar.setBackground(new java.awt.Color(238, 99, 99));
        navbar.setForeground(new java.awt.Color(1, 1, 1));

        sistemPakar.setFont(new java.awt.Font("Nunito", 1, 14)); // NOI18N
        sistemPakar.setForeground(new java.awt.Color(254, 254, 254));
        sistemPakar.setText("SistemPakar.");

        btnKeluar.setBackground(new java.awt.Color(254, 254, 254));
        btnKeluar.setText("Keluar");

        javax.swing.GroupLayout navbarLayout = new javax.swing.GroupLayout(navbar);
        navbar.setLayout(navbarLayout);
        navbarLayout.setHorizontalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(sistemPakar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKeluar)
                .addGap(26, 26, 26))
        );
        navbarLayout.setVerticalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navbarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sistemPakar)
                    .addComponent(btnKeluar))
                .addContainerGap())
        );

        dataPenyakit.setFont(new java.awt.Font("Nunito", 1, 14)); // NOI18N
        dataPenyakit.setText("Data Penyakit");

        btnTambahPenyakit.setBackground(new java.awt.Color(254, 254, 254));
        btnTambahPenyakit.setText("Tambah");

        dataGejala.setFont(new java.awt.Font("Nunito", 1, 14)); // NOI18N
        dataGejala.setText("Data Gejala");

        btnTambahGejala.setBackground(new java.awt.Color(254, 254, 254));
        btnTambahGejala.setText("Tambah");

        dataAturan.setFont(new java.awt.Font("Nunito", 1, 14)); // NOI18N
        dataAturan.setText("Aturan");

        btnTambahAturan.setBackground(new java.awt.Color(254, 254, 254));
        btnTambahAturan.setText("Tambah");

        tabelAturan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No", "Jika", "Maka"
            }
        ));
        scrollAturan.setViewportView(tabelAturan);

        dataUser.setFont(new java.awt.Font("Nunito", 1, 14)); // NOI18N
        dataUser.setText("Data User");

        btnTambahUser.setBackground(new java.awt.Color(254, 254, 254));
        btnTambahUser.setText("Tambah");

        tabelUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null,},
                {null, null, null, null,},
                {null, null, null, null,},
                {null, null, null, null,}
            },
            new String [] {
                "No", "ID User", "Role", "Nama",
            }
        ));
        scrollUser.setViewportView(tabelUser);

        javax.swing.GroupLayout bgWhiteLayout = new javax.swing.GroupLayout(bgWhite);
        bgWhite.setLayout(bgWhiteLayout);
        bgWhiteLayout.setHorizontalGroup(
            bgWhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgWhiteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bgWhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dataPenyakit)
                    .addComponent(scrollAturan, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambahAturan)
                    .addComponent(dataAturan)
                    .addComponent(btnTambahGejala)
                    .addComponent(btnTambahPenyakit)
                    .addComponent(dataGejala))
                .addGroup(bgWhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgWhiteLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(bgWhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataUser)
                            .addComponent(btnTambahUser)))
                    .addGroup(bgWhiteLayout.createSequentialGroup()
                        .addGap(464, 464, 464)
                        .addComponent(scrollUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bgWhiteLayout.setVerticalGroup(
            bgWhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgWhiteLayout.createSequentialGroup()
                .addComponent(navbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgWhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataPenyakit)
                    .addComponent(dataUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgWhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahPenyakit)
                    .addComponent(btnTambahUser))
                .addGap(18, 18, 18)
                .addComponent(scrollUser, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataGejala)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTambahGejala)
                .addGap(237, 237, 237)
                .addComponent(dataAturan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTambahAturan)
                .addGap(9, 9, 9)
                .addComponent(scrollAturan, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgWhite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgWhite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgWhite;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnTambahAturan;
    private javax.swing.JButton btnTambahGejala;
    private javax.swing.JButton btnTambahPenyakit;
    private javax.swing.JButton btnTambahUser;
    private javax.swing.JLabel dataAturan;
    private javax.swing.JLabel dataGejala;
    private javax.swing.JLabel dataPenyakit;
    private javax.swing.JLabel dataUser;
    private javax.swing.JPanel navbar;
    private javax.swing.JScrollPane scrollAturan;
    private javax.swing.JScrollPane scrollUser;
    private javax.swing.JLabel sistemPakar;
    private javax.swing.JTable tabelAturan;
    private javax.swing.JTable tabelUser;
    // End of variables declaration//GEN-END:variables
}
