/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sikar.view;

import com.sikar.model.Penyakit;
import com.sikar.dao.PenyakitDAO;
import com.sikar.dao.PenyakitDAOMySQL;

import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.List;
import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

import java.sql.SQLException;
/**
 *
 * @author admin01
 */
public class TambahPenyakitFrame extends javax.swing.JFrame {
    private PenyakitDAO PenyakitDAO;
    private List<Penyakit> recPenyakit = new ArrayList<Penyakit>();
    private static final long serialVersionUID = 1L;
    /**
     * Creates new form TambahPenyakitFrame
     */
    public TambahPenyakitFrame() {
        initComponents();
        PenyakitDAO  = new PenyakitDAOMySQL();
        initStatus();

        tabelPenyakit.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                int row = tabelPenyakit.getSelectedRow();
                if (row != -1) {
                    textFill();
                }
            }
        });
    }

    public void loadAllPenyakit() {
        try {
            recPenyakit = PenyakitDAO.getAll();
        } catch (SQLException e) {
            Logger.getLogger(TambahPenyakitFrame.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    void tableFill() {
        Object data[][] = new Object[recPenyakit.size()][5];
        int x = 0, no = 1;
        for (Penyakit p : recPenyakit) {
            data[x][0] = no++;
            data[x][1] = p.getKodePenyakit();
            data[x][2] = p.getNamaPenyakit();
            data[x][3] = p.getDeskripsiPenyakit();
            data[x][4] = p.getSolusi();
            x++;
        }
        String judul[] = {"No","Kode Penyakit", "Nama Penyakit", "Deskripsi Penyakit", "Solusi"};
        tabelPenyakit.setModel(new DefaultTableModel(data, judul));
    }

    public void textFill() {
        Penyakit p = recPenyakit.get(tabelPenyakit.getSelectedRow());
        txtKodePenyakit.setText(p.getKodePenyakit());
        txtNamaPenyakit.setText(p.getNamaPenyakit());
        txtDeskripsiPenyakit.setText(p.getDeskripsiPenyakit());
        txtSolusi.setText(p.getSolusi());
    }

    public void clear() {
        txtKodePenyakit.setText("");
        txtNamaPenyakit.setText("");
        txtDeskripsiPenyakit.setText("");
        txtSolusi.setText("");
    }

    void initStatus() {
        clear();
        loadAllPenyakit();
        tableFill();
    }

    void refresh_page() {
        this.dispose();
        TambahPenyakitFrame f = new TambahPenyakitFrame();
        f.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgBlue = new javax.swing.JPanel();
        navbar = new javax.swing.JPanel();
        TambahPenyakit = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();
        DataPenyakitBox = new javax.swing.JPanel();
        DataPenyakit = new javax.swing.JLabel();
        txtKodePenyakit = new javax.swing.JTextField();
        labelKodePenyakit = new javax.swing.JLabel();
        labelNamaPenyakit = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDeskripsiPenyakit = new javax.swing.JTextArea();
        labelDeskripsiPenyakit = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSolusi = new javax.swing.JTextArea();
        labelSolusi = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        txtNamaPenyakit = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelPenyakit = new javax.swing.JTable();
        btnEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bgBlue.setBackground(new java.awt.Color(5, 101, 201));

        navbar.setBackground(new java.awt.Color(254, 254, 254));

        TambahPenyakit.setFont(new java.awt.Font("Nunito", 1, 14)); // NOI18N
        TambahPenyakit.setText("Tambah Penyakit");

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navbarLayout = new javax.swing.GroupLayout(navbar);
        navbar.setLayout(navbarLayout);
        navbarLayout.setHorizontalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(TambahPenyakit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 420, Short.MAX_VALUE)
                .addComponent(btnKembali)
                .addGap(36, 36, 36))
        );
        navbarLayout.setVerticalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TambahPenyakit)
                    .addComponent(btnKembali))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        DataPenyakitBox.setBackground(new java.awt.Color(254, 254, 254));

        DataPenyakit.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        DataPenyakit.setText("Data Penyakit");

        labelKodePenyakit.setFont(new java.awt.Font("Nunito", 0, 13)); // NOI18N
        labelKodePenyakit.setText("Kode Penyakit :");

        labelNamaPenyakit.setFont(new java.awt.Font("Nunito", 0, 13)); // NOI18N
        labelNamaPenyakit.setText("Nama Penyakit :");

        txtDeskripsiPenyakit.setColumns(20);
        txtDeskripsiPenyakit.setLineWrap(true);
        txtDeskripsiPenyakit.setRows(5);
        jScrollPane1.setViewportView(txtDeskripsiPenyakit);

        labelDeskripsiPenyakit.setFont(new java.awt.Font("Nunito", 0, 13)); // NOI18N
        labelDeskripsiPenyakit.setText("Deskripsi :");

        txtSolusi.setColumns(20);
        txtSolusi.setLineWrap(true);
        txtSolusi.setRows(5);
        jScrollPane2.setViewportView(txtSolusi);

        labelSolusi.setFont(new java.awt.Font("Nunito", 0, 13)); // NOI18N
        labelSolusi.setText("Solusi :");

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        tabelPenyakit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tabelPenyakit);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DataPenyakitBoxLayout = new javax.swing.GroupLayout(DataPenyakitBox);
        DataPenyakitBox.setLayout(DataPenyakitBoxLayout);
        DataPenyakitBoxLayout.setHorizontalGroup(
            DataPenyakitBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataPenyakitBoxLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(DataPenyakitBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DataPenyakitBoxLayout.createSequentialGroup()
                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
                    .addGroup(DataPenyakitBoxLayout.createSequentialGroup()
                        .addGroup(DataPenyakitBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DataPenyakitBoxLayout.createSequentialGroup()
                                .addGroup(DataPenyakitBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelNamaPenyakit)
                                    .addComponent(labelDeskripsiPenyakit)
                                    .addComponent(labelSolusi))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(DataPenyakitBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1)
                                    .addComponent(txtNamaPenyakit)))
                            .addComponent(DataPenyakit, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DataPenyakitBoxLayout.createSequentialGroup()
                                .addComponent(labelKodePenyakit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtKodePenyakit)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        DataPenyakitBoxLayout.setVerticalGroup(
            DataPenyakitBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataPenyakitBoxLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(DataPenyakit)
                .addGap(18, 18, 18)
                .addGroup(DataPenyakitBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKodePenyakit)
                    .addComponent(txtKodePenyakit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DataPenyakitBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNamaPenyakit)
                    .addComponent(txtNamaPenyakit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(DataPenyakitBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DataPenyakitBoxLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DataPenyakitBoxLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(labelDeskripsiPenyakit)))
                .addGroup(DataPenyakitBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DataPenyakitBoxLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DataPenyakitBoxLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(labelSolusi)))
                .addGap(23, 23, 23)
                .addGroup(DataPenyakitBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bgBlueLayout = new javax.swing.GroupLayout(bgBlue);
        bgBlue.setLayout(bgBlueLayout);
        bgBlueLayout.setHorizontalGroup(
            bgBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bgBlueLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DataPenyakitBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bgBlueLayout.setVerticalGroup(
            bgBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgBlueLayout.createSequentialGroup()
                .addComponent(navbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(DataPenyakitBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgBlue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bgBlue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        this.dispose();
        AdminFrame f = new AdminFrame();
        f.setVisible(true);
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        try {
            Penyakit p = new Penyakit();
            p.setKodePenyakit(txtKodePenyakit.getText());
            p.setNamaPenyakit(txtNamaPenyakit.getText());
            p.setDeskripsiPenyakit(txtDeskripsiPenyakit.getText());
            p.setSolusi(txtSolusi.getText());
            PenyakitDAO.insert(p);
            JOptionPane.showMessageDialog(null, "Berhasil, Data ditambahkan!");
            clear();
            refresh_page();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
            Logger.getLogger(TambahPenyakitFrame.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        try {
            Penyakit p = new Penyakit();
            p.setKodePenyakit(txtKodePenyakit.getText());
            p.setNamaPenyakit(txtNamaPenyakit.getText());
            p.setDeskripsiPenyakit(txtDeskripsiPenyakit.getText());
            p.setSolusi(txtSolusi.getText());
            PenyakitDAO.update(p);
            JOptionPane.showMessageDialog(null, "Berhasil, Data ditambahkan!");
            clear();
            refresh_page();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
            Logger.getLogger(TambahPenyakitFrame.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        try {
            JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin menghapus data?");
            Penyakit p = recPenyakit.get(tabelPenyakit.getSelectedRow());
            PenyakitDAO.delete(p.getKodePenyakit());
            JOptionPane.showMessageDialog(null, "Berhasil, Data dihapus!");
            refresh_page();
        } catch (SQLException e) {
            Logger.getLogger(TambahPenyakitFrame.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahPenyakitFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahPenyakitFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahPenyakitFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahPenyakitFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahPenyakitFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DataPenyakit;
    private javax.swing.JPanel DataPenyakitBox;
    private javax.swing.JLabel TambahPenyakit;
    private javax.swing.JPanel bgBlue;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnTambah;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelDeskripsiPenyakit;
    private javax.swing.JLabel labelKodePenyakit;
    private javax.swing.JLabel labelNamaPenyakit;
    private javax.swing.JLabel labelSolusi;
    private javax.swing.JPanel navbar;
    private javax.swing.JTable tabelPenyakit;
    private javax.swing.JTextArea txtDeskripsiPenyakit;
    private javax.swing.JTextField txtKodePenyakit;
    private javax.swing.JTextField txtNamaPenyakit;
    private javax.swing.JTextArea txtSolusi;
    // End of variables declaration//GEN-END:variables
}
